In [ ]:
## Numpy 배열로 5명 학생의 4과목 성적표를 만들고, 축(axis)기준 통계를 산출하시오.


아래 1차원 리스트는 학생 5명이 4개 과목(국어, 영어, 수학, 과학 순)에서 받은 점수를 이어 붙인 것입니다.

Numpy만 사용하여(반복문 사용 금지) 다음을 순서대로 수행하고 결과를 출력하세요.

scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]


1. 위 리스트를 5행 4열 ndarray로 변환하고 shape, ndim, size, dtype을 출력하시오.

2. 학생 별 평균과 과목 별 평균을 각각 구하시오.

3. 전체에서 가장 높은 점수와 그 점수가 몇 번째 학생·몇 번째 과목인지 구하시오.

4. 전체 평균, 표준편차, 분산을 구하시오.

5. 평균이 80점 이상인 학생의 인덱스와 인원수를 구하고, 해당 학생들의 성적만 잘라내어 출력하시오.

6. 90점 이상인 점수의 개수, 100점 이상인 점수가 하나라도 있는지, 모든 점수가 60점 이상인지를 판별하시오.

7. 90점 이상은 'A', 80점 이상은 'B', 나머지는 'C'로 변환한 등급 배열을 만드시오.

In [1]:
import numpy as np

In [67]:
# 문제 1-1번
scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]


x = np.array(scores).reshape(5, 4)
print(x.shape, x.ndim, x.size, x.dtype)

(5, 4) 2 20 int64


In [ ]:
# 문제 1-2번
student_means = np.mean(x, axis=1)
subject_means = np.mean(x, axis=0)
print(student_means)
print(subject_means)

[88.5  73.75 93.5  63.75 83.25]
[80.  82.2 79.8 80.2]


In [ ]:
# 문제 1-3번
print(x.max()) # 최대값
index_max = np.where(x == x.max()) # 최대값 위치
result = int(index_max[0][0]), int(index_max[1][0])
print(result)

99
(2, 1)


In [32]:
# 문제 1-4번
print(np.mean(x)) # 평균
print(np.std(x)) # 표준편차
print(np.var(x)) # 분산

80.55
11.825713509129164
139.84750000000003


In [48]:
# 문제 1-5번
index_student = np.where(student_means >= 80)[0] # 조건에 맞는 위치
count = np.sum(student_means >= 80)

print(index_student)
print(count)
print(x[student_means>=80])

[0 2 4]
3
[[88 92 79 95]
 [92 99 95 88]
 [85 80 78 90]]


In [49]:
# 문제 1-6번
count = np.sum(x >= 90)

print(count) # 90점 이상인 갯수
print(np.any(x >= 100)) # 하나라도 참이어야 참
print(np.all(x >= 60)) # 모든 요소가 참이어야 참

6
False
False


In [58]:
# 문제 1-7번
grade = np.where(x >= 90, 'A', np.where(x >= 80, 'B', 'c'))  
print(grade)

[['B' 'A' 'c' 'A']
 ['c' 'c' 'B' 'c']
 ['A' 'A' 'A' 'B']
 ['c' 'c' 'c' 'c']
 ['B' 'B' 'c' 'A']]


In [ ]:
## 8x8 난수 배열을 흑백 이미지로 가정하고 슬라이싱,이진화,좌우반전을 구하시오


0~255 사이의 정수 난수로 이루어진 8행 8열 배열을 흑백 이미지 데이터라고 가정합니다. 채점 결과를 동일하게 맞추기 위해 반드시 아래 시드를 먼저 실행하세요.


import numpy as np
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))


1. 생성한 img를 출력하시오.

2. 이미지 정중앙의 4×4 영역만 잘라내어 출력하시오.

3. 짝수 번째 행(0, 2, 4, 6행)만 뽑아내시오.

4. 128 이상인 픽셀은 255(흰색), 미만인 픽셀은 0(검은색)으로 바꾼 이진화 배열을 만드시오.

5. 이진화 결과에서 흰색 픽셀과 검은색 픽셀의 개수를 각각 세시오.

6. 원본 이미지를 좌·우 절반으로 분할하시오.

7. 분할한 두 조각의 순서를 바꿔 다시 이어 붙여 좌우가 뒤바뀐 이미지를 만드시오.

8. 원본 이미지를 1차원으로 펼친 뒤 앞 10개 값과 shape을 출력하시오.

9. 128 이상인 픽셀만 골라내어 그 개수와 평균값을 구하시오.



In [59]:
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))

In [60]:
# 문제 2-1번
print(img)

[[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]]


In [61]:
# 문제 2-2번
center_img = img[2:6, 2:6]
print(center_img)

[[241 158 111 247]
 [ 11  28  91  39]
 [102 218 244  42]
 [ 86 119  69 157]]


In [90]:
# 문제 2-3번
print(img[::2])   # 모든 행은 2칸씩 띄워서 가져옴, 해당 행의 열은 전체 다 가져옴

[[136 250  96 128  27  36 190 183]
 [165 252 241 158 111 247 202 110]
 [183  73 102 218 244  42  31  97]
 [ 54 132  57  86  54 254 148 126]]


In [74]:
# 문제 2-4번
new_array = np.where(img >= 128, 255, 0)
print(new_array)

[[255 255   0 255   0   0 255 255]
 [  0   0 255   0 255   0   0 255]
 [255 255 255 255   0 255 255   0]
 [  0   0   0   0   0   0   0   0]
 [255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255   0 255]
 [  0 255   0   0   0 255 255   0]
 [255   0   0   0 255 255 255 255]]


In [75]:
# 문제 2-5번
count_w = np.sum(new_array==255)
count_b = np.sum(new_array==0)
print(count_w, count_b)

28 36


In [92]:
# 문제 2-6번
left_img = img[:, :4]
right_img = img[:, 4:]
print(left_img)
print(right_img)

[[136 250  96 128]
 [ 41 127 193  60]
 [165 252 241 158]
 [ 95 111  11  28]
 [183  73 102 218]
 [150  27  86 119]
 [ 54 132  57  86]
 [136  18  97  90]]
[[ 27  36 190 183]
 [227  74  66 224]
 [111 247 202 110]
 [ 91  39  54 114]
 [244  42  31  97]
 [ 69 157  61 243]
 [ 54 254 148 126]
 [202 135 176 232]]


In [81]:
# 문제 2-7번
re_img = np.concatenate([right_img, left_img], axis=1)
print(re_img)

[[ 27  36 190 183 136 250  96 128]
 [227  74  66 224  41 127 193  60]
 [111 247 202 110 165 252 241 158]
 [ 91  39  54 114  95 111  11  28]
 [244  42  31  97 183  73 102 218]
 [ 69 157  61 243 150  27  86 119]
 [ 54 254 148 126  54 132  57  86]
 [202 135 176 232 136  18  97  90]]


In [86]:
# 문제 2-8번
raveled_img = img.ravel()
print(raveled_img[:10], raveled_img.shape)

[136 250  96 128  27  36 190 183  41 127] (64,)


In [89]:
# 문제 2-9번
filter_img = img[img >= 128]
print(filter_img.size)
print(np.mean(filter_img))

28
193.07142857142858


In [95]:
## 지점별 판매 데이터에 브로드캐스트와 행렬 연산을 적용해 매출을 분석하시오
# 3개 지점이 4개 제품을 판매한 수량과, 제품별 단가가 다음과 같습니다.

sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

In [97]:
total = sales * price  # 2차원 * 1차원
print(total)

[[180000 240000 225000 120000]
 [300000 450000 450000  60000]
 [112500 180000 600000 190000]]


In [105]:
sales_sum = np.sum(total, axis=1)  # 각 지점별 매출 합계
sales_means = np.mean(total, axis=1)  # 각 지점별 매출 평균
product_sum = np.sum(total, axis=0)  # 각 제품별 매출 합계
product_means = np.mean(total, axis=0)  # 각 제품별 매출 평균

print(sales_sum)
print(sales_means)
print(product_sum)
print(product_means)

[ 765000 1260000 1082500]
[191250. 315000. 270625.]
[ 592500  870000 1275000  370000]
[197500.         290000.         425000.         123333.33333333]


In [ ]:
# 각 지점의 제품별 매출과 제품별 매출평균과의 편차 분석
product_gap = total - np.mean(total, axis=0)
print(product_gap)


[[ -17500.          -50000.         -200000.           -3333.33333333]
 [ 102500.          160000.           25000.          -63333.33333333]
 [ -85000.         -110000.          175000.           66666.66666667]]


In [ ]:
# z-점수 정규화
m = np.mean(total, axis=1, keepdims=True)   # 각 지점별 매출 평균
s = np.std(total, axis=1, keepdims=True)    # 각 지점별 매출 표준편차
z = (total - m) / s
print(np.round(z, 2))

[[-0.24  1.04  0.72 -1.53]
 [-0.09  0.85  0.85 -1.6 ]
 [-0.82 -0.47  1.71 -0.42]]


In [ ]:
# 최대 매출 지점, 최대 매출 제품 
print(np.argmax(sales_sum))  # B지점
print(np.argmax(product_sum))  # 제품3

1
2
